run:
  timeout: 5m

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - bin
    - dist
    - testdata

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net.Conn).Close
      - (*os.File).Close
      - (database/sql).(*sql.DB).Close
      - (database/sql).(*sql.Rows).Close
      - (database/sql).(*sql.Stmt).Close
