version: 2
project_name: mnemonic
builds:
  - id: mnemonic
    main: ./cmd/mnemonic
    binary: mnemonic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
archives:
  - id: bundles
    ids:
      - mnemonic
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
