repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: go fmt
        args: [-l]
      - id: go-vet
        name: go vet
        args: [-all]
      - id: go-mod-tidy
        name: go mod tidy
      - id: go-build
        name: go build
        args: [./...]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.8
    hooks:
      - id: golangci-lint
        name: golangci-lint
        args:
          - --timeout=5m
          - --config=.golangci.yml
          - ./...
